# Generated by Django 5.2.1 on 2025-06-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilReview',
            new_name='Review',
        ),
        migrations.AlterModelTable(
            name='profil',
            table='profil',
        ),
    ]
