# Generated by Django 5.2.1 on 2025-07-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_profil_bio_alter_profil_utilisateur_delete_review'),
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='profils',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='profil.profil'),
            preserve_default=False,
        ),
    ]
